version: '3.7'

services:
  spark-master:
    image: bitnami/spark:3.4
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_CONF_DIR=/opt/bitnami/spark/conf
      - SPARK_MASTER_HOST=spark-master
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=/tmp/spark-events
    ports:
      - "8080:8080"
      - "4040:4040"
    networks:
      - spark-network
  spark-worker:
    image: bitnami/spark:3.4
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=3G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=2G
    depends_on:
      - spark-master
    networks:
      - spark-network

  jupyter:
    build: .
    ports:
      - "8888:8888"
    networks:
      - spark-network
    volumes:
      - ./local_lake:/home/jovyan/work
      - ./notebooks:/home/jovyan/
      - .:/opt/spark/work-dir
      - /tmp/spark/spark-events:/tmp/spark-events
    depends_on:
      - spark-master
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"

  spark-history-server:
    image: rangareddy1988/spark-history-server:${VERSION:-latest}
    container_name: spark-history-server
    environment:
      - SPARK_HISTORY_FS_LOGDIRECTORY=/tmp/spark-events
      - SPARK_HISTORY_UI_PORT=18080
    ports:
      - 18080:18080
    networks:
      - spark-network
    volumes:
      - /tmp/spark/spark-events:/tmp/spark-events
      - /tmp/spark/spark-history-server-logs:/var/log/spark

networks:
  spark-network:
    driver: bridge
